from tkinter import *

root = Tk()
root.title("GUI Example")
root.geometry("300x250")
root.option_add('*font', 'tahoma 10 bold')
frame = Frame(root)
frame.config(background="cyan")
frame.place(width=300, height=250, x=0, y=0)
root.option_add("*foreground", "navy")
root.option_add("*background", "cyan")
root.option_add('*Label.font', 'tahoma 11 bold underline')
label1 = Label(frame, text="Your Favorite Sport")
label1.grid(column=0, row=0, padx=80, pady=10)
var1 = IntVar()
c1 = Checkbutton(frame, text="แบดมินตัน", width=10, variable=var1, anchor=W)
c1.grid(column=0, row=1, padx=80, pady=10)
var2 = IntVar()
c2 = Checkbutton(frame, text="เทนนิส", width=10, variable=var2, anchor=W)
c2.grid(column=0, row=2, padx=80, pady=10)
var3 = IntVar()
c3 = Checkbutton(frame, text="วอลเล่ย์บอล", width=10, variable=var3, anchor=W)
c3.grid(column=0, row=3, padx=80, pady=10)
root.mainloop()
