from tkinter import *

root = Tk()
root.title("GUI Example")
root.geometry("300x250")
root.option_add('*font', 'tahoma 10 bold')
frame = Frame(root)
frame.config(background="cyan")
frame.place(width=300, height=250, x=0, y=0)
var1 = StringVar(value="S0001")
entry1 = Entry(frame, textvariable=var1, width=20, state=DISABLED)
entry1.pack(padx=10, pady=10)
var2 = StringVar(value="12345")
entry2 = Entry(frame, textvariable=var2, width=20, show="*")
entry2.pack(padx=10, pady=10)
text3 = Text(frame, width=20)
text3.insert(INSERT, "ยังเรียนกันอยู่ เนาะ?\n ให้ยกมือด้วย")
text3.pack(padx=10, pady=10)
root.mainloop()
